services:
  inventory-management-server:
    image: inventory-management-server
    container_name: inventory-management-server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src:rw
      - ./server/prisma:/app/prisma:rw
    networks:
      - client-side
  inventory-management-client:
    image: inventory-management-client
    container_name: inventory-management-client
    build:
      context: ./client
    # env_file:
    #   - ./client/.env
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app:rw
    networks:
      - client-side
    depends_on:
      - inventory-management-server

networks:
  client-side: {}
