export
 const CATEGORY = {
	NAME: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		MUST_BE_ALPHANUMERIC: 'MUST_BE_ALPHANUMERIC',
		MIN_LENGTH: 'MIN_LENGTH',
		MAX_LENGTH: 'MAX_LENGTH',
		REQUIRED: 'REQUIRED',
		NOT_FOUND: 'NOT_FOUND',
	},
	DESCRIPTION: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		MIN_LENGTH: 'MIN_LENGTH',
		MAX_LENGTH: 'MAX_LENGTH',
		REQUIRED: 'REQUIRED',
		INVALID: 'INVALID',
	},
	PARENT: {
		INVALID: 'INVALID',
	},
	CREATE: {
		PERMISION_DENIED: 'PERMISION_DENIED',
		GENERAL: 'GENERAL',
		INVALID_OPERATION: 'INVALID_OPERATION',
		IMAGE_URL: {
			INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
		},
		PARENT_CATEGORY: 'PARENT_CATEGORY',
	},
	FIND: {
		GENERAL: 'GENERAL',
	},
	DELETE: {
		GENERAL: 'GENERAL',
	},
	UPDATE: {
		NO_SUPPLIER_FOUND: 'NO_SUPPLIER_FOUND',
		GENERAL: 'GENERAL',
	},
};