export const DEPOT = {
	CREATE: {
		NAME: {
			MUST_BE_STRING: 'MUST_BE_STRING',
			REQUIRED: 'REQUIRED',
			MIN_LENGTH: 'MIN_LENGTH',
			MAX_LENGTH: 'MAX_LENGTH',
		},
		DESCRIPTION: {
			MUST_BE_STRING: 'MUST_BE_STRING',
		},
		IMAGE_URL: {
			MUST_BE_URL: 'MUST_BE_URL',
		},
	}
}