export const DEPOT = {
	CREATE: {
		NAME: {
			MUST_BE_STRING: 'MUST_BE_STRING',
			REQUIRED: 'REQUIRED',
			MIN_LENGTH: 'MIN_LENGTH',
			MAX_LENGTH: 'MAX_LENGTH',
		},
		DESCRIPTION: {
			MUST_BE_STRING: 'MUST_BE_STRING',
		},
		IMAGE_URL: {
			MUST_BE_URL: 'MUST_BE_URL',
		},
		GENERAL: 'GENERAL',
	},
	FIND_ALL: {
		NO_DEPOT_FOUND: 'NO_DEPOT_FOUND',
	},
	FIND_ONE: {
		NO_DEPOT_FOUND: 'NO_DEPOT_FOUND',
	},
	REMOVE: {
		NO_DEPOT_FOUND: 'NO_DEPOT_FOUND',
		GENERAL: 'GENERAL',
	},
	UPDATE: {
		NO_DEPOT_FOUND: 'NO_DEPOT_FOUND',
		GENERAL: 'GENERAL',
		USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
		INVALID_USER: 'INVALID_USER',
	},
}