export const SIGNIN = {
	USERNAME: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		MUST_BE_ALPHANUMERIC: 'MUST_BE_ALPHANUMERIC',
		MIN_LENGTH: 'MIN_LENGTH',
		MAX_LENGTH: 'MAX_LENGTH',
		REQUIRED: 'REQUIRED',
		NOT_FOUND: 'NOT_FOUND',
	},
	PASSWORD: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		WEAK: 'WEAK',
		MIN_LENGTH: 'MIN_LENGTH',
		REQUIRED: 'REQUIRED',
		INVALID: 'INVALID',
	},
};