export const SIGNUP = {
	USERNAME: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		MUST_BE_ALPHANUMERIC: 'MUST_BE_ALPHANUMERIC',
		MIN_LENGTH: 'MIN_LENGTH',
		MAX_LENGTH: 'MAX_LENGTH',
		REQUIRED: 'REQUIRED',
		ALREADY_EXISTS: 'ALREADY_EXISTS',
	},
	PASSWORD: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		WEAK: 'WEAK',
		MIN_LENGTH: 'MIN_LENGTH',
		REQUIRED: 'REQUIRED',
	},
	FIRST_NAME: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		REQUIRED: 'REQUIRED',
	},
	LAST_NAME: {
		MUST_BE_STRING: 'MUST_BE_STRING',
		REQUIRED: 'REQUIRED',
	},
}